# Generated by Django 4.2.1 on 2023-05-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerApi', '0003_remove_customer_orderscnt_customer_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='customerApi.customer')),
            ],
            options={
                'verbose_name': 'incentive',
                'verbose_name_plural': 'incentives',
            },
        ),
    ]
