# Generated by Django 4.2.1 on 2023-05-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('tel', models.PositiveIntegerField()),
                ('DOB', models.DateField()),
                ('tablebook', models.PositiveIntegerField()),
                ('orders', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
