# Generated by Django 4.2.1 on 2023-05-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApi', '0002_customer_orderscnt_incentive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='orderscnt',
        ),
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Incentive',
        ),
    ]
