# Generated by Django 4.2.1 on 2023-05-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_restaurants_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='RESTAURANT_STATUS',
            field=models.CharField(choices=[('A', 'Activate'), ('D', 'Deactivate')], max_length=20),
        ),
    ]
